CREATE TABLE [dbo].[Contact]
(
	[Id] INT NOT NULL IDENTITY, 
	[LastName] NVARCHAR(50) NOT NULL,
	[FirstName] NVARCHAR(50) NOT NULL,
	[Email] NVARCHAR(384) NULL,
	[Phone] NVARCHAR(30) NULL,
	[UserId] INT NOT NULL,
    CONSTRAINT [PK_Contact] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_Contact_User] FOREIGN KEY ([UserId])
		REFERENCES [dbo].[User](Id)
)
